/**
 * 
 */
package constant;

import jpa.TbProcessTrackDetailType;

/**
 * Enum for  ProcessTrackDetailType (Mapped IDs fromTable {@link TbProcessTrackDetailType}
 * 
 * @author tmolina
 * @since 07-02-2011
 */
public enum ProcessTrackDetailType {
	
	CLIENT_CREATION(100L), 
	CLIENT_DOCUMENT_RECEPTION(101L), 
	CLIENT_DOCUMENT_VERIFICATION(102L), 
	CLIENT_DOCUMENT_VERIFICATION_FAIL(103L), 
	CLIENT_ACCOUNT_CREATION(104L), 
	CLIENT_CONSIGMENT_REGISTER(105L), 
	CLIENT_CONSIGMENT_APPROVED(106L), 
	CLIENT_CONSIGMENT_REJECTION(107L),
	CLIENT_DEVICE_PAY(108L),
	DEVICE_CREATION(200L), 
	DEVICE_RECHARGE(201L), 
	DEVICE_ACCOUNT_ASSOCIATION(202L), 
	DEVICE_BLACK_LIST(203L),
	DEVICE_ENTRY_ORDER(204L),
	DEVICE_STATE_CHANGE(205L),
	DEVICE_INITIALIZATION(206L),
	CUSTOMIZATION_CREATION(300L), 
	CUSTOMIZATION_REJECTION(301L), 
	CUSTOMIZATION_CONFIRMATION(302L), 
	CUSTOMIZATION(303L), 
	CUSTOMIZATION_INSTALLATION(304L),
	CUSTOMIZATION_DEVICE_ASSOCIATION(305L), 
	INCLUSION_CREATION(400L),
	INCLUSION_SENT(401L),
	INCLUSION_DETAILS_INITIALIZED(402L),
	PURCHASE_ORDER_CREATION(500L),
	PURCHASE_ORDER_CONSIGMENT_ASSOCIATION(501L),
	PURCHASE_ORDER_DETAIL_DONE(502L),
	MY_CLIENT_CREATION(600L),
	MY_CLIENT_DOCUMENT_RECEPTION(601L),
	MY_CLIENT_DOCUMENT_VERIFICATION(602L), 
	MY_CLIENT_DOCUMENT_VERIFICATION_FAIL(603L),
	NOTE_CREATION(604L),
	CHANGE_LOW_BALANCE_THRESHOLD(606L),
	OBJECTION_ACCOUNT(605L),
	REQUEST_CLOSE_ACCOUNT(607L),
	CLOSE_ACCOUNT(608L),
	REACTIVATION_ACCOUNT(609L),
	AUTHOMATHIC_RECHARGE(610L),
	BANK_ACCOUNT_CLIENT(611L),
	BANK_ACCOUNT(612L),
	INIT_RECHARGE(614L),
	CLIENT_ACCOUNT_ASSOCIATION(613L),
	MANUAL_RECHARGE(615L),
	DEVICE_ACCOUNT_DISABLE(616L),
	HOLIDAY(617L),
	ADJUSTMENT_OBJECTION(618L),
	DOCUMENT(619L),
	RESET_PASSWORD(620L),
	CHANGE_PASSWORD(621L),
	MANUAL_DISTRIBUTION(622L),
	MANAGEMENT_NOTIFICATION(623L),
	VEHICLES(624L),
	VEHICLES_ADMIN(625L),
	DEVICE_ACCOUNT_ENROLL(626L),
	DEVICE_ACCOUNT_CHANGE(627L),
	DEVICE_ACCOUNT_REPLACE(628L),
	UPDATE_LOW_BALANCE(629L),
	DATA_POLICIES(630L),
	UPDATE_MINIMUM_BALANCE(631L),
	PASSWORD_MANAGEMENT(632L),
	RESET_QUESTIONS(633L),
	UPDATE_LOW_BALANCE_ADMIN(634L),
	AGREEMENT(636L),
	CHANNEL(637L),
	RE_CHANNEL_AGREEMENT(638L),
	AUTOMATIC_PROGRAMMING_ENTITIES(639L);
	
	 private Long id;

	 /**
	  * 
	  * @param id
	  */
	 private ProcessTrackDetailType(Long id) {
	   this.id = id;
	 }

	 /**
	  * 
	  * @return id
	  */
	 public Long getId() {
	  	 return id;
	 }
}