-- Generated by Oracle SQL Developer Data Modeler Version: 2.0.0 Build: 570
--   at:        2010-06-10 10:42:23
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




CREATE TABLE RE_DE_REGISTRATION 
    ( 
     RE_DE_REGISTRATION_ID NUMBER (19)  NOT NULL , 
     DEVICE_ID NUMBER (19)  NOT NULL , 
     RECEIVER_ID NUMBER (19)  NOT NULL 
    ) 
;



ALTER TABLE RE_DE_REGISTRATION 
    ADD CONSTRAINT RE_DE_REGISTRATION_PK PRIMARY KEY ( RE_DE_REGISTRATION_ID ) ;



CREATE TABLE TB_DEVICE 
    ( 
     DEVICE_ID NUMBER (19)  NOT NULL , 
     DEVICE_CODE VARCHAR2 (50 BYTE)  NOT NULL , 
     DEVICE_CURRENT_BALANCE NUMBER (19)  NOT NULL , 
    
--  Type 0: TAG Device
--  Type 1: TSC Device-Especial
--  Type 2: TSC Device-Exento
--  Type 3: TSC Device-Tarjeta COLOMBIA
--  Type 4: TSC Device-Tarjeta PISA
--  Type 5: TSC Device-Tarjeta COVIANDES
 DEVICE_TYPE NUMBER (1)  NOT NULL , 
    
--  State 0: Dispositivo en Preorden
--  State 2: Dispositivo personalizado
--  State 4: Dispositivo instalado
--  State 6: Dispositivo activado
--  State 7: Dispositivo desactivado
--  State 9: Dispositivo en lista negra
 DEVICE_STATE NUMBER (1)  NOT NULL 
    ) 
;



ALTER TABLE TB_DEVICE 
    ADD CONSTRAINT DEVICE_PK PRIMARY KEY ( DEVICE_ID ) ;



CREATE TABLE TB_LANE 
    ( 
     LANE_ID NUMBER (19)  NOT NULL , 
     STATION_ID NUMBER (19)  NOT NULL , 
     LANE_CODE VARCHAR2 (20 BYTE)  NOT NULL , 
     LANE_NAME VARCHAR2 (20 BYTE)  NOT NULL 
    ) 
;



ALTER TABLE TB_LANE 
    ADD CONSTRAINT TB_LANE_PK PRIMARY KEY ( LANE_ID ) ;



CREATE TABLE TB_RECEIVER 
    ( 
     RECEIVER_ID NUMBER (19)  NOT NULL , 
    
--  Receiver Name
--  NOMBRECONCESION_NUMERO-CONTRATO_NOMBRE-APLICATIVO
 RECEIVER_NAME VARCHAR2 (50 BYTE) , 
     RECEIVER_IPV4 VARCHAR2 (15 BYTE)  NOT NULL , 
    
--  State 0: Active
--  State 1: Inactive
 RECEIVER_STATE NUMBER (1)  NOT NULL 
    ) 
;



ALTER TABLE TB_RECEIVER 
    ADD CONSTRAINT RECEIVER_PK PRIMARY KEY ( RECEIVER_ID ) ;



CREATE TABLE TB_STATION 
    ( 
     STATION_ID NUMBER (19)  NOT NULL , 
     RECEIVER_ID NUMBER (19)  NOT NULL , 
     STATION_CODE VARCHAR2 (20 BYTE)  NOT NULL , 
     STATION_NAME VARCHAR2 (20 BYTE)  NOT NULL 
    ) 
;



ALTER TABLE TB_STATION 
    ADD CONSTRAINT TB_STATION_PK PRIMARY KEY ( STATION_ID ) ;



CREATE TABLE TB_TRANSACTION 
    ( 
     TRANSACTION_ID NUMBER (19)  NOT NULL , 
     DEVICE_ID NUMBER (19)  NOT NULL , 
     LANE_ID NUMBER (19)  NOT NULL , 
    
--  Type 0: Transaccion de Recarga
--  Type 1: Transaccion de Pago
--  Type 2: Transaccion de Consulta
 TRANSACTION_TYPE NUMBER (1)  NOT NULL , 
     PREVIOUS_BALANCE NUMBER (19)  NOT NULL , 
     NEW_BALANCE NUMBER (19)  NOT NULL , 
     TRANSACTION_VALUE NUMBER (19)  NOT NULL , 
     TRANSACTION_TIME TIMESTAMP  NOT NULL , 
     BACK_OFFICE_TIME TIMESTAMP , 
     TRANSACTION_FFUF VARCHAR2 (50 BYTE) 
    ) 
;



ALTER TABLE TB_TRANSACTION 
    ADD CONSTRAINT TRANSACTION_PK PRIMARY KEY ( TRANSACTION_ID ) ;



CREATE TABLE TR_RE_NOTIFIER 
    ( 
     TR_RE_ID NUMBER (19)  NOT NULL , 
     RECEIVER_ID NUMBER (19)  NOT NULL , 
     TRANSACTION_ID NUMBER (19)  NOT NULL , 
    
--  Notification_status 0: new Task
--  Notification_status 1: Task notified
 NOTIFICATION_STATUS NUMBER (1)  NOT NULL 
    ) 
;



ALTER TABLE TR_RE_NOTIFIER 
    ADD CONSTRAINT TR_RE_NOTIFIER_PK PRIMARY KEY ( TR_RE_ID ) ;




ALTER TABLE RE_DE_REGISTRATION 
    ADD CONSTRAINT DEVICE_REGISTRATION FOREIGN KEY 
    ( 
     DEVICE_ID
    ) 
    REFERENCES TB_DEVICE 
    ( 
     DEVICE_ID
    ) 
;



ALTER TABLE TB_LANE 
    ADD CONSTRAINT LANE_STATION FOREIGN KEY 
    ( 
     STATION_ID
    ) 
    REFERENCES TB_STATION 
    ( 
     STATION_ID
    ) 
;



ALTER TABLE TB_TRANSACTION 
    ADD CONSTRAINT LANE_TRANSACTION FOREIGN KEY 
    ( 
     LANE_ID
    ) 
    REFERENCES TB_LANE 
    ( 
     LANE_ID
    ) 
;



ALTER TABLE TR_RE_NOTIFIER 
    ADD CONSTRAINT RECEIVER_NOTIFIER FOREIGN KEY 
    ( 
     RECEIVER_ID
    ) 
    REFERENCES TB_RECEIVER 
    ( 
     RECEIVER_ID
    ) 
;



ALTER TABLE RE_DE_REGISTRATION 
    ADD CONSTRAINT RECEIVER_REGISTRATION FOREIGN KEY 
    ( 
     RECEIVER_ID
    ) 
    REFERENCES TB_RECEIVER 
    ( 
     RECEIVER_ID
    ) 
;



ALTER TABLE TB_STATION 
    ADD CONSTRAINT RECEIVER_STATION FOREIGN KEY 
    ( 
     RECEIVER_ID
    ) 
    REFERENCES TB_RECEIVER 
    ( 
     RECEIVER_ID
    ) 
;



ALTER TABLE TB_TRANSACTION 
    ADD CONSTRAINT TRANSACTION_DEVICE FOREIGN KEY 
    ( 
     DEVICE_ID
    ) 
    REFERENCES TB_DEVICE 
    ( 
     DEVICE_ID
    ) 
;



ALTER TABLE TR_RE_NOTIFIER 
    ADD CONSTRAINT TRANSACTION_NOTIFIER FOREIGN KEY 
    ( 
     TRANSACTION_ID
    ) 
    REFERENCES TB_TRANSACTION 
    ( 
     TRANSACTION_ID
    ) 
;


    
    
    
    
    
    
    

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                              8
-- CREATE VIEW                              0
-- CREATE PROCEDURE                         0
-- CREATE TRIGGER                           0
-- CREATE STRUCTURED TYPE                   0
-- CREATE COLLECTION TYPE                   0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE SNAPSHOT                          0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
