
package com.grupoaval.telepeajes.accounts.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AcctStatusImplService", targetNamespace = "http://v1.accounts.telepeajes.grupoaval.com/", wsdlLocation = "http://localhost:8996/AcctStatus?wsdl")
public class AcctStatusImplService
    extends Service
{

    private final static URL ACCTSTATUSIMPLSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8996/AcctStatus?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        ACCTSTATUSIMPLSERVICE_WSDL_LOCATION = url;
    }

    public AcctStatusImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AcctStatusImplService() {
        super(ACCTSTATUSIMPLSERVICE_WSDL_LOCATION, new QName("http://v1.accounts.telepeajes.grupoaval.com/", "AcctStatusImplService"));
    }

    /**
     * 
     * @return
     *     returns AcctStatusModSoap
     */
    @WebEndpoint(name = "AcctStatusImplPort")
    public AcctStatusModSoap getAcctStatusImplPort() {
        return (AcctStatusModSoap)super.getPort(new QName("http://v1.accounts.telepeajes.grupoaval.com/", "AcctStatusImplPort"), AcctStatusModSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AcctStatusModSoap
     */
    @WebEndpoint(name = "AcctStatusImplPort")
    public AcctStatusModSoap getAcctStatusImplPort(WebServiceFeature... features) {
        return (AcctStatusModSoap)super.getPort(new QName("http://v1.accounts.telepeajes.grupoaval.com/", "AcctStatusImplPort"), AcctStatusModSoap.class, features);
    }

}
