
package com.grupoaval.telepeajes.payments.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "RechargeNotificationSoap", targetNamespace = "urn://grupoaval.com/telepeajes/payments/v1/")
@XmlSeeAlso({
    com.grupoaval.telepeajes.xsd.ifx.ObjectFactory.class,
    com.grupoaval.telepeajes.payments.v1.ObjectFactory.class
})
public interface RechargeNotificationSoap {


    /**
     * 
     * @param rechargeNotificationAddRq
     * @return
     *     returns com.grupoaval.telepeajes.payments.v1.RechargeNotificationAddRsType
     */
    @WebMethod(action = "urn://grupoaval.com/telepeajes/payments/v1/notifyRecharge")
    @WebResult(name = "RechargeNotificationAddRs", targetNamespace = "urn://grupoaval.com/telepeajes/payments/v1/")
    @RequestWrapper(localName = "notifyRecharge", targetNamespace = "urn://grupoaval.com/telepeajes/payments/v1/", className = "com.grupoaval.telepeajes.payments.v1.NotifyRecharge")
    @ResponseWrapper(localName = "notifyRechargeResponse", targetNamespace = "urn://grupoaval.com/telepeajes/payments/v1/", className = "com.grupoaval.telepeajes.payments.v1.NotifyRechargeResponse")
    public RechargeNotificationAddRsType notifyRecharge(
        @WebParam(name = "RechargeNotificationAddRq", targetNamespace = "urn://grupoaval.com/telepeajes/payments/v1/")
        RechargeNotificationAddRqType rechargeNotificationAddRq);

}
