
package com.grupoaval.telepeajes.payments.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "RechargeSoap", targetNamespace = "urn://grupoaval.com/telepeajes/payments/v1/")
@XmlSeeAlso({
    com.grupoaval.telepeajes.payments.v1.ObjectFactory.class,
    com.grupoaval.telepeajes.xsd.ifx.ObjectFactory.class
})
public interface RechargeSoap {


    /**
     * 
     * @param rechargeAddRq
     * @return
     *     returns com.grupoaval.telepeajes.payments.v1.RechargeAddRsType
     */
    @WebMethod(action = "urn://grupoaval.com/telepeajes/payments/v1/addRecharge")
    @WebResult(name = "RechargeAddRs", targetNamespace = "urn://grupoaval.com/telepeajes/payments/v1/")
    @RequestWrapper(localName = "addRecharge", targetNamespace = "urn://grupoaval.com/telepeajes/payments/v1/", className = "com.grupoaval.telepeajes.payments.v1.AddRecharge")
    @ResponseWrapper(localName = "addRechargeResponse", targetNamespace = "urn://grupoaval.com/telepeajes/payments/v1/", className = "com.grupoaval.telepeajes.payments.v1.AddRechargeResponse")
    public RechargeAddRsType addRecharge(
        @WebParam(name = "RechargeAddRq", targetNamespace = "urn://grupoaval.com/telepeajes/payments/v1/")
        RechargeAddRqType rechargeAddRq);

}
