package constant;

public enum EmailProcess {

	PREREGISTRATION(1L),
	PASSWORD_CHANGE(2L),
	DOCUMENT_VALIDATION_APPROVED(3L),
	DOCUMENT_VALIDATION_REJECTED(4L),
	ACCOUNT_CREATION(5L),
	ACCOUNT_ACTIVATION_SUCCESSFUL(6L),
	ACCOUNT_ACTIVATION_REJECTED(7L),
	LOW_BALANCE(8L),
	RESOURCE_ALLOCATION_SUCCESSFUL(9L),
	RESOURCE_ALLOCATION_REJECTED(10L),
	CANCEL_ACCOUNT(11L),
	ASSOCIATION_DEVICE(12L),
	UTILIZATION(13L),
	BANK_PRODUCT_REGISTRATION(14L),
	CREATE_NOTIFICATION(15L),
	CREATE_OBJECTION(16L),
	PAYMENT_DEVICE(17L),
	CREATE_INVOICE(18L),
	REGISTER_USER(19L),
	DOCUMENT_SEND(20L),
	NOTES(21L),
	CANCEL_ACCOUNT_APPLY(22L),
	REACTIVATION_ACCOUNT(26L),
	DISABLE_ACCOUNT_DEVICE(23L),
	UPDATE_OBJECTION(24L),
	DELETE_OBJECTION(25L),
	CREATE_USER_CLIENT(27L),
	CHANGE_DEVICE(28L),
	REPLACEMENT_DEVICE(29L),
	DISSOCIATION_ACCOUNT(30L),
	ENROL_DEVICES_MASSIVE(31L),
	SUCCESSFUL_ONLINE_RECHARGE(53L),
	ERROR_RECHARGE_ONLINE(54L),
	ONLINE_RECHARGE_REVERT(55L),
	ERROR_ONLINE_RECHARGE_REVERT(56L),
	
	ERROR_AUTO_FREQ(66L),  // NTF-10
	REC_FREQ_APROBADA_AUT(67L), // NTF-13
	ERROR_RECARG_FREQ_AUT(68L), // NTF-12
	
	ERROR_AUT_SALD(69L), // NTF-10
	REC_SALD_APROBADA_AUT(70L), // NTF-13
	ERROR_RECARG_SALD_AUT(71L), // NTF-12
	
	AVAL_URL_USED_BALANCE(78L),  // NTF - 16
	
	ERROR_INACTIVE_ELEMENTS(88L), // NTF - 39
	AVAL_URL_NOT_EXIST(89L), // NTF - 15
	AVAL_URL_USED_FREQUENCY(90L), // NTF - 16
	
	FREQUENCY_PREPAID_SCHEDULED_TOPUP_ERROR(91L), // NTF - 23
	MBALACE_PREPAID_SCHEDULED_TOPUP_ERROR(92L), // NTF - 23
	
	FREQUENCY_PREPAID_SCHEDULED_TOPUP_REJECTED(93L), //NTF - 24
	MBALACE_PREPAID_SCHEDULED_TOPUP_REJECTED(94L), // NTF - 24
	
	FREQUENCY_PREPAID_SCHEDULED_TOPUP_APROVED(95L), // NTF - 25
	MBALACE_PREPAID_SCHEDULED_TOPUP_APROVED(96L), // NTF - 25
	
	MBALANCE_PREPAID_SCHEDULED_TOPUP_PROCESS_ERROR(97L),
	MBALANCE_POSTPAID_SCHEDULED_TOPUP_PROCESS_ERROR(98L),
	
	FREQUENCY_POSTPAID_SCHEDULED_TOPUP_ERROR(99), // NTF - 30
	MBALACE_POSTPAID_SCHEDULED_TOPUP_ERROR(100L), // NTF - 30
	
	FREQUENCY_POSTPAID_SCHEDULED_TOPUP_REJECTED(101L), //NTF - 31
	MBALACE_POSTPAID_SCHEDULED_TOPUP_REJECTED(102L), // NTF - 31
	
	FREQUENCY_POSTPAID_SCHEDULED_TOPUP_APROVED(103L), // NTF - 32
	MBALACE_POSTPAID_SCHEDULED_TOPUP_APROVED(104L), // NTF - 32
	
	FREQUENCY_POSTPAID_SCHEDULED_TOPUP_PROCESS_ERROR(105L);
		
	private Long id;
	
	private EmailProcess(long id) {
		   this.id = id;
	}
	
	public Long getId() {
	  	 return id;
	 }
}
