
package com.grupoaval.telepeajes.accounts.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AccountAdminImplService", targetNamespace = "http://v1.accounts.telepeajes.grupoaval.com/", wsdlLocation = "http://localhost:8995/AccountAdmin?wsdl")
public class AccountAdminImplService
    extends Service
{

    private final static URL ACCOUNTADMINIMPLSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8995/AccountAdmin?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        ACCOUNTADMINIMPLSERVICE_WSDL_LOCATION = url;
    }

    public AccountAdminImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountAdminImplService() {
        super(ACCOUNTADMINIMPLSERVICE_WSDL_LOCATION, new QName("http://v1.accounts.telepeajes.grupoaval.com/", "AccountAdminImplService"));
    }

    /**
     * 
     * @return
     *     returns AccountAdminSoap
     */
    @WebEndpoint(name = "AccountAdminImplPort")
    public AccountAdminSoap getAccountAdminImplPort() {
        return (AccountAdminSoap)super.getPort(new QName("http://v1.accounts.telepeajes.grupoaval.com/", "AccountAdminImplPort"), AccountAdminSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountAdminSoap
     */
    @WebEndpoint(name = "AccountAdminImplPort")
    public AccountAdminSoap getAccountAdminImplPort(WebServiceFeature... features) {
        return (AccountAdminSoap)super.getPort(new QName("http://v1.accounts.telepeajes.grupoaval.com/", "AccountAdminImplPort"), AccountAdminSoap.class, features);
    }

}
