
-- Lista de Destinatarios del BackOffice

Insert into TB_RECEIVER (RECEIVER_ID,RECEIVER_NAME,RECEIVER_IPV4,RECEIVER_STATE) values (1,'COVIANDE_444-94_VIAL','192.168.3.199',0);
Insert into TB_RECEIVER (RECEIVER_ID,RECEIVER_NAME,RECEIVER_IPV4,RECEIVER_STATE) values (2,'COVIANDE_444-94-PEAJE','192.168.1.70',0);

-- Lista de estaciones de recaudo pertenecientes a los destinatarios

Insert into TB_STATION (STATION_ID,RECEIVER_ID,STATION_CODE,STATION_NAME) values (1,1,'62','BOQUERON1');
Insert into TB_STATION (STATION_ID,RECEIVER_ID,STATION_CODE,STATION_NAME) values (2,1,'63','BOQUERON2');
Insert into TB_STATION (STATION_ID,RECEIVER_ID,STATION_CODE,STATION_NAME) values (3,1,'64','P.QUETAME');
Insert into TB_STATION (STATION_ID,RECEIVER_ID,STATION_CODE,STATION_NAME) values (4,1,'65','PIPIRAL');
Insert into TB_STATION (STATION_ID,RECEIVER_ID,STATION_CODE,STATION_NAME) values (5,2,'62','BOQUERON1');
Insert into TB_STATION (STATION_ID,RECEIVER_ID,STATION_CODE,STATION_NAME) values (6,2,'63','BOQUERON2');
Insert into TB_STATION (STATION_ID,RECEIVER_ID,STATION_CODE,STATION_NAME) values (7,2,'64','P.QUETAME');
Insert into TB_STATION (STATION_ID,RECEIVER_ID,STATION_CODE,STATION_NAME) values (8,2,'65','PIPIRAL');

-- Lista de carriles en donde se encuetran instalados los dispositivos de pago electrónico.

Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (1,1,'0','0');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (2,1,'1','1');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (3,1,'2','2');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (4,1,'3','3');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (5,1,'4','4');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (6,1,'5','5');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (7,1,'6','6');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (8,2,'0','0');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (9,2,'1','1');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (10,2,'2','2');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (11,3,'0','0');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (12,3,'1','1');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (13,3,'2','2');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (14,3,'3','3');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (15,3,'4','4');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (16,3,'5','5');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (17,3,'6','6');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (18,4,'0','0');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (19,4,'1','1');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (20,4,'2','2');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (21,4,'3','3');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (22,4,'4','4');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (23,4,'5','5');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (24,4,'6','6');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (25,5,'0','0');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (26,5,'1','1');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (27,5,'2','2');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (28,5,'3','3');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (29,5,'4','4');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (30,5,'5','5');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (31,5,'6','6');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (32,6,'0','0');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (33,6,'1','1');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (34,6,'2','2');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (35,7,'0','0');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (36,7,'1','1');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (37,7,'2','2');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (38,7,'3','3');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (39,7,'4','4');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (40,7,'5','5');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (41,7,'6','6');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (42,8,'0','0');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (43,8,'1','1');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (44,8,'2','2');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (45,8,'3','3');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (46,8,'4','4');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (47,8,'5','5');
Insert into TB_LANE (LANE_ID,STATION_ID,LANE_CODE,LANE_NAME) values (48,8,'6','6');

-- Lista de dispositivos electrónicos registrados en el Back-Office

Insert into TB_DEVICE (DEVICE_ID,DEVICE_CODE,DEVICE_CURRENT_BALANCE,DEVICE_TYPE,DEVICE_STATE) values (1,'50918521',100000,0,6);
Insert into TB_DEVICE (DEVICE_ID,DEVICE_CODE,DEVICE_CURRENT_BALANCE,DEVICE_TYPE,DEVICE_STATE) values (2,'50918532',100000,0,6);
Insert into TB_DEVICE (DEVICE_ID,DEVICE_CODE,DEVICE_CURRENT_BALANCE,DEVICE_TYPE,DEVICE_STATE) values (3,'50918523',100000,0,6);
Insert into TB_DEVICE (DEVICE_ID,DEVICE_CODE,DEVICE_CURRENT_BALANCE,DEVICE_TYPE,DEVICE_STATE) values (4,'50918528',100000,0,6);
Insert into TB_DEVICE (DEVICE_ID,DEVICE_CODE,DEVICE_CURRENT_BALANCE,DEVICE_TYPE,DEVICE_STATE) values (5,'50918524',100000,0,6);
Insert into TB_DEVICE (DEVICE_ID,DEVICE_CODE,DEVICE_CURRENT_BALANCE,DEVICE_TYPE,DEVICE_STATE) values (6,'50918525',100000,0,6);
Insert into TB_DEVICE (DEVICE_ID,DEVICE_CODE,DEVICE_CURRENT_BALANCE,DEVICE_TYPE,DEVICE_STATE) values (7,'50918526',100000,0,6);

-- Asociación de dispositivos a los destinatarios interesados.

Insert into RE_DE_REGISTRATION (RE_DE_REGISTRATION_ID,DEVICE_ID,RECEIVER_ID) values (1,1,1);
Insert into RE_DE_REGISTRATION (RE_DE_REGISTRATION_ID,DEVICE_ID,RECEIVER_ID) values (2,2,1);
Insert into RE_DE_REGISTRATION (RE_DE_REGISTRATION_ID,DEVICE_ID,RECEIVER_ID) values (3,3,1);
Insert into RE_DE_REGISTRATION (RE_DE_REGISTRATION_ID,DEVICE_ID,RECEIVER_ID) values (4,4,1);
Insert into RE_DE_REGISTRATION (RE_DE_REGISTRATION_ID,DEVICE_ID,RECEIVER_ID) values (5,5,1);
Insert into RE_DE_REGISTRATION (RE_DE_REGISTRATION_ID,DEVICE_ID,RECEIVER_ID) values (6,6,1);
Insert into RE_DE_REGISTRATION (RE_DE_REGISTRATION_ID,DEVICE_ID,RECEIVER_ID) values (7,7,1);
Insert into RE_DE_REGISTRATION (RE_DE_REGISTRATION_ID,DEVICE_ID,RECEIVER_ID) values (8,1,2);
Insert into RE_DE_REGISTRATION (RE_DE_REGISTRATION_ID,DEVICE_ID,RECEIVER_ID) values (9,2,2);
Insert into RE_DE_REGISTRATION (RE_DE_REGISTRATION_ID,DEVICE_ID,RECEIVER_ID) values (10,3,2);
Insert into RE_DE_REGISTRATION (RE_DE_REGISTRATION_ID,DEVICE_ID,RECEIVER_ID) values (11,4,2);
Insert into RE_DE_REGISTRATION (RE_DE_REGISTRATION_ID,DEVICE_ID,RECEIVER_ID) values (12,5,2);
Insert into RE_DE_REGISTRATION (RE_DE_REGISTRATION_ID,DEVICE_ID,RECEIVER_ID) values (13,6,2);
Insert into RE_DE_REGISTRATION (RE_DE_REGISTRATION_ID,DEVICE_ID,RECEIVER_ID) values (14,7,2);


commit;