
package com.grupoaval.telepeajes.payments.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RechargeNotificationImplService", targetNamespace = "http://v1.payments.telepeajes.grupoaval.com/", wsdlLocation = "http://localhost:8998/RechargeNotification?wsdl")
public class RechargeNotificationImplService
    extends Service
{

    private final static URL RECHARGENOTIFICATIONIMPLSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8998/RechargeNotification?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        RECHARGENOTIFICATIONIMPLSERVICE_WSDL_LOCATION = url;
    }

    public RechargeNotificationImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RechargeNotificationImplService() {
        super(RECHARGENOTIFICATIONIMPLSERVICE_WSDL_LOCATION, new QName("http://v1.payments.telepeajes.grupoaval.com/", "RechargeNotificationImplService"));
    }

    /**
     * 
     * @return
     *     returns RechargeNotificationSoap
     */
    @WebEndpoint(name = "RechargeNotificationImplPort")
    public RechargeNotificationSoap getRechargeNotificationImplPort() {
        return (RechargeNotificationSoap)super.getPort(new QName("http://v1.payments.telepeajes.grupoaval.com/", "RechargeNotificationImplPort"), RechargeNotificationSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RechargeNotificationSoap
     */
    @WebEndpoint(name = "RechargeNotificationImplPort")
    public RechargeNotificationSoap getRechargeNotificationImplPort(WebServiceFeature... features) {
        return (RechargeNotificationSoap)super.getPort(new QName("http://v1.payments.telepeajes.grupoaval.com/", "RechargeNotificationImplPort"), RechargeNotificationSoap.class, features);
    }

}
